// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5rtKEHtlnFl-1hBXSDxrxsVE4wLHZWUs',
    appId: '1:472830303078:web:0e3901e066cd9213bd06a7',
    messagingSenderId: '472830303078',
    projectId: 'dayinbloom-4dde1',
    authDomain: 'dayinbloom-4dde1.firebaseapp.com',
    storageBucket: 'dayinbloom-4dde1.firebasestorage.app',
    measurementId: 'G-H3F457558P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlKLbQgud9sUrXoU_w_AaVgGDMrFN0ZCk',
    appId: '1:472830303078:android:a23d7a968cbffcd0bd06a7',
    messagingSenderId: '472830303078',
    projectId: 'dayinbloom-4dde1',
    storageBucket: 'dayinbloom-4dde1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWcMMueR6bej0_VbsGtVUHiin5TWNXIMA',
    appId: '1:472830303078:ios:97b4a617078262bdbd06a7',
    messagingSenderId: '472830303078',
    projectId: 'dayinbloom-4dde1',
    storageBucket: 'dayinbloom-4dde1.firebasestorage.app',
    iosBundleId: 'com.example.dayInBloomV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWcMMueR6bej0_VbsGtVUHiin5TWNXIMA',
    appId: '1:472830303078:ios:97b4a617078262bdbd06a7',
    messagingSenderId: '472830303078',
    projectId: 'dayinbloom-4dde1',
    storageBucket: 'dayinbloom-4dde1.firebasestorage.app',
    iosBundleId: 'com.example.dayInBloomV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5rtKEHtlnFl-1hBXSDxrxsVE4wLHZWUs',
    appId: '1:472830303078:web:0e5a33f1d7d5fbeebd06a7',
    messagingSenderId: '472830303078',
    projectId: 'dayinbloom-4dde1',
    authDomain: 'dayinbloom-4dde1.firebaseapp.com',
    storageBucket: 'dayinbloom-4dde1.firebasestorage.app',
    measurementId: 'G-MJP9YTLXDC',
  );
}
